services:
  postgres:
    image: postgres:17
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zonafit123
      POSTGRES_DB: zonafit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gym-net

volumes:
  postgres-data:

networks:
  gym-net:
